### ISSUE TITLE
Straatnaam en nummer afzonderlijk uitlezen

### ISSUE THREAD

**Issue by PeterSarens** [jdt/EID.Wrapper#10]
Is het mogelijk om de straatnaam en nummer afzonderlijk uit te lezen op een Belgische e-ID?

**Comment by JohanRVT** [comment]
Beste,
momenteel is het (data.FirstCard.StreetAndNumber), dus straat én huisnummer in één veld op de chip en zit er nog de gemeente tussen haakjes bij wat met Googlemaps problemen geeft. Ik smijt dus met een VBA procedure achteraf alles wat er tussen haakjes zit weg. Je zou dus hetzelfde kunnen proberen te doen met het huisnummer door te kijken op alles wat achter de laatste spatie komt indien het huisnummer niet eindigt op een letter. Maar geheel failsafe ga je dat niet krijgen denk ik want er zijn veel variaties op de huis-met-bus nummers. Ik laat alles van straat en huisnr gewoon in één regel laten staan. Wat is het voordeel om dat apart te doen?

**Comment by PeterSarens** [comment]
Beste, 
alvast bedankt voor het antwoord. 
Ik werk momenteel met een toepassing waarin straat en huisnummer 2 aparte velden zijn. Vandaar dat het handig zou zijn om die 2 ook apart te kunnen lezen van de e-ID. 


Van: "JohanRVT" <notifications@github.com> 
Aan: "jdt/EID.Wrapper" <EID.Wrapper@noreply.github.com> 
Cc: "peter" <peter.sarens@telenet.be>, "Author" <author@noreply.github.com> 
Verzonden: Dinsdag 18 juli 2017 14:29:39 
Onderwerp: Re: [jdt/EID.Wrapper] Straatnaam en nummer afzonderlijk uitlezen (#10) 



Beste, 
momenteel is het (data.FirstCard.StreetAndNumber), dus straat én huisnummer in één veld op de chip en zit er nog de gemeente tussen haakjes bij wat met Googlemaps problemen geeft. Ik smijt dus met een VBA procedure achteraf alles wat er tussen haakjes zit weg. Je zou dus hetzelfde kunnen proberen te doen met het huisnummer door te kijken op alles wat achter de laatste spatie komt indien het huisnummer niet eindigt op een letter. Maar geheel failsafe ga je dat niet krijgen denk ik want er zijn veel variaties op de huis-met-bus nummers. Ik laat alles van straat en huisnr gewoon in één regel laten staan. Wat is het voordeel om dat apart te doen?

**Comment by jdt** [comment]
De wrapper gaat enkel uitlezen wat er op de EID-kaart voorzien is en (bewust) geen opsplitsing of manipulatie van data doen. Straat en huisnummer staan enkel in één veld op de kaart en dus worden die ook zo uitgelezen.
