### ISSUE TITLE
Issue reading eid issued after march 2014

### ISSUE THREAD

**Issue by jdt** [jdt/EID.Wrapper#7]
Hi @didierr, could you elaborate on the issue you commented on at https://github.com/jdt/EID.Wrapper/issues/2#issuecomment-163957797? What exactly is the problem?

I've opened a new issue to track this separately.

**Comment by didierr** [comment]
Hi @jdt ,

When I try to read a belgian eid card issued before march 2014, the code below display the name of the person :

```
Dim EIDlib1 As New EIDLIBCTRLLib.EIDlib
Dim lHandle As Long
Dim RetStatus As New EIDLIBCTRLLib.RetStatus
Dim MapColID As New EIDLIBCTRLLib.MapCollection
Dim CertifCheck As New EIDLIBCTRLLib.CertifCheck
Dim strName As String

Set RetStatus = EIDlib1.Init("", 0, 0, lHandle)
Set RetStatus = EIDlib1.GetID(MapColID, CertifCheck)
strName = MapColID.GetValue("Name")
msgbox strName 

Set RetStatus = EIDlib1.Exit
```

But, when I try to read a belgian eid card issued after march 2014 with the same code, the name is empty (and firstname, address, zip code, national number, ... also)

Is it clearer ?

Best regards,

Didier

**Comment by jdt** [comment]
If you use this wrapper, the code you provided becomes obsolete. The wrapper provides a way to read data from the cards that does not rely on the EIDLIBCTRLLib, which no longer works for cards issued after March 2014. Read the part on installation at https://github.com/jdt/EID.Wrapper#installation and check out the basic usage examples at https://github.com/jdt/EID.Wrapper#usage to rework your code to the wrapper.
